# fly.toml file generated for theauschwitzproject on 2023-04-07T21:06:51-04:00

app = "theauschwitzproject"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ewr"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
